# Generated by Django 2.1.15 on 2020-07-29 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField(max_length=50)),
                ('Call', models.TextField(max_length=50)),
                ('Address', models.TextField(max_length=50)),
            ],
        ),
    ]
